schema: []
generates:
  # ./src/generated.ts:
  #   schema:
  #     - http://localhost:1337/v1/graphql:
  #         headers:
  #           x-hasura-admin-secret: nhost-admin-secret
  #           x-hasura-role: user
  #   documents: 'src/**/!(*.d).{ts,tsx}'
  #   config:
  #     namingConvention:
  #       typeNames: change-case-all#pascalCase
  #       transformUnderscore: true
  #   plugins:
  #     - typescript
  #     - typescript-operations
  #     - typescript-vue-apollo-smart-ops
  ./functions/_sdk.ts:
    schema:
      - http://localhost:1337/v1/graphql:
          headers:
            x-hasura-admin-secret: nhost-admin-secret
    documents: 'functions/**/_*.graphql'
    config:
      namingConvention:
        typeNames: change-case-all#pascalCase
        transformUnderscore: true
      gqlImport: graphql-request#gql

    plugins:
      - typescript
      - typescript-operations
      - typescript-graphql-request
